Milestone 1: Creating header and headline of my Portfolio
Dangelo-JAN/DangeloArrivillaga-Portfolio pull request #1
Opened 2022-02-10 15:08 UTC by Dangelo-JAN

## Creating my portfolio milestone 1: Creating header and headline of my Portfolio

In this mileston we:

- Add .gitignore
- Add linters
- Add index.html
- Add style.css

2022-02-10 18:17 UTC, Wes-Isaac requested changes
Hi @Dangelo-JAN , 

Impressive work so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

### 📝👌 Your project highlights 🔥😎

- Linters are on point ✔
- Proper use of GitHub flow 👌
- Awesome design 🙌

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 18:17 UTC, Wes-Isaac commented on index.html
> +        </div>
- [ ] Great job utilizing semantic tags, However, it is one of the project requirements to use an `<a></a>` tag for the logo kindly fix that.

2022-02-10 18:17 UTC, Wes-Isaac commented on index.html
> +    </div>
- [ ] Great job implementing the markup, however, it is best to follow [HTML & CSS best practices,](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) one of which is to use HTML5 semantic tags (e.g., header, nav, section) over `div`s.

2022-02-10 18:17 UTC, Wes-Isaac commented on style.css
> +
- [ ] setting a fixed width is creating an unnecessary space on your site better to use flexible units, Kindly style the section so that it looks similar to the design.

Your Implementation | Figma Design
:---: | :---:


![image](https://user-images.githubusercontent.com/59416136/153469669-3908ce7d-fc0f-404d-a20a-dc180a7eb996.png)|![image](https://user-images.githubusercontent.com/59416136/153470437-d49c3bb9-034c-492d-9105-128ffb3b7c8a.png)

2022-02-10 21:36 UTC, BenMukebo requested changes
### Hi  @Dangelo-JAN , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 21:36 UTC, BenMukebo commented on style.css
> +}
- [ ] As said by the previous review, kindly remove this width as it is breaking your page in when on the mobile version, see images below ⬇️
 #### [See this ](https://www.youtube.com/watch?v=NeThtWARdnY) for a short understanding of how to start a web page from a mobile-first approach

- [ ] With the width enabled
<img width="289" alt="bg" src="https://user-images.githubusercontent.com/79058364/153493406-95c227a7-b55f-4915-b514-f348d1768c38.png">

- [ ] With the width disabled
<img width="288" alt="cr" src="https://user-images.githubusercontent.com/79058364/153493441-f8e34aed-f233-4859-b75a-3a9cddf4bb82.png">

2022-02-10 21:36 UTC, BenMukebo commented on index.html
> +        </div>
- [ ]  Since it represents the navbar, I would suggest you wrap them inside a `nav` tag

2022-02-10 21:36 UTC, BenMukebo commented on index.html
> +  <div class="contenedor">
- [ OPTIANL] please, you should consider the body as your main parent, the first child should be the header followed by the main and the footer, please, refer to the HTML and CSS best practice provided in earlier lessons

2022-02-10 21:36 UTC, BenMukebo commented on style.css
> +  font-weight: 700;
- [ ] Right at the top of this h1 tag, I suggest you tag the body element and set the padding and margin to `0`, as you can see in the image below, the is a margin that makes your page have that small with space around, see the image below 🔽 

<img width="707" alt="Screen Shot 2022-02-10 at 23 25 38" src="https://user-images.githubusercontent.com/79058364/153500144-159aef05-8e74-4855-8a5e-ccf43b95996f.png">

2022-02-10 23:32 UTC, Wes-Isaac approved these changes
Hi @Dangelo-JAN , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 23:32 UTC, Wes-Isaac commented on style.css
> +}
- [ ] [_OPTIONAL_] By default pages have margin and padding, this sometimes might mess up the page. So it's better to remove them and set your own margin and padding. Check this [link ](https://stackoverflow.com/questions/30208335/removing-body-margin-in-css#:~:text=The%20right%20answer%20for%20this%20question%20is%20%22css%20reset%22.&text=It%20removes%20all%20default%20margin,holds%20barred%2C%20regardless%20of%20browser.)for more info

2022-02-11 00:21 UTC, Dangelo-JAN commented
@BenMukebo Thanks for all the support in the reviewers, I will take notes for all your recomendations

2022-02-11 00:21 UTC, merged